### ISSUE TITLE
Foreign key issue

### ISSUE THREAD

**Issue by DigiAngel** [google/binnavi#106] opened 2017-04-01 17:54 UTC
Upon importing an IDA db, I get a "violates foreign key constraint" message.  Did I miss a step?

![screenshot from 2017-04-01 11-46-15](https://cloud.githubusercontent.com/assets/947191/24581091/d4714de6-16d1-11e7-804b-b30e7e28d08b.png)

This is with IDA 6.9...thank you.

**Comment by luckycat889** [comment] 2017-04-20 13:46
I do see the exact same error when running BinNavi on a .i64 (ARM64) IDA file.
I am running IDA Pro 6.95 and postgres 9.6. Connection to postgres seems all fine.

Thanks in advance.....

**Comment by agatcenko** [comment] 2017-04-26 11:52
Same error =( win7x64, ida pro 6.95, postgres 9.6

**Comment by thomasdullien** [comment] 2017-04-27 14:36
Hey there,

looking into it. I *think* it is a matter of configuring the Mysql backend engine, should have updates shortly.

**Comment by cblichmann** [comment] 2017-04-27 14:55
MySQL? What year is it :) s/MySQL/PostgreSQL/

**Comment by thomasdullien** [comment] 2017-04-27 15:23
Err. Postgres. Sorry :-)

**Comment by thomasdullien** [comment] 2017-05-15 08:17
Looking at it now. Apologies for the delay, only now getting around to it.

**Comment by thomasdullien** [comment] 2017-05-15 09:33
Hey there,

would it potentially possible to enable postgres statement logging (http://stackoverflow.com/questions/722221/how-to-log-postgresql-queries), create a log of the attempted export, and post it here?

In the meantime I will try to setup a Win7x64 VM :)

**Comment by thomasdullien** [comment] 2017-05-15 09:39
Ah, I can reproduce on linux here now.

**Comment by thomasdullien** [comment] 2017-05-15 10:12
This appears to be an issue in the current BinExport code. I am investigating further -- in my case I have a "position" field of 5, for an instruction like .text:5A2CF715                 cmp     [ebp+arg_4], 0FFFFFFFFh -- this is clearly nonsensical, as there are only 2 operands.

**Comment by thomasdullien** [comment] 2017-05-15 12:03
Hey there,

this seems to be a regression / bug in the binexport code introduced in https://github.com/google/binexport/commit/622ce57529819d0e3f69de3b1531d5db7c4c6fbf#diff-b69fe242252cb8a02ce4b800ed65facb

I will try to see what is going wrong.

**Comment by thomasdullien** [comment] 2017-05-15 15:27
Hey there,

I fixed the first issue, but more broke in the meantime. The quickest way to get going is probably to use binexport8 from the repo (see in the history), working on a fix for binexport9 though.

**Comment by DigiAngel** [comment] 2017-05-15 15:46
Thanks...nice to see some work on this :) :+1:

**Comment by thomasdullien** [comment] 2017-05-15 18:45
Hey there,

ok, the current stopgap solution while I try to figure out how to get binexport9 to work with BinNavi is the following:

1) Download the binexport8 pre-built plugin from the first checkin of BinNavi in this github, and
place it in your IDA plugins directory
2) Patch CBinExportImporter.java:
private static final String BINEXPORT_VERSION = "zynamics_binexport_9";
private static final String BINEXPORT_VERSION = "zynamics_binexport_**8**";

You should now be able to import. I am hoping to get binexport9 to work again this week.

**Comment by DigiAngel** [comment] 2017-05-15 20:04
Thanks a bunch...I'll report my results in a few hours :)

**Comment by DigiAngel** [comment] 2017-05-16 01:11
Ah...that CBinExportImporter.java is I'm guessing from the source...ya I'm using the release versions :(

**Comment by thomasdullien** [comment] 2017-05-16 11:01
Hey there,

ok, I have pushed a fix for the issue into a fork of binexport here:
https://github.com/thomasdullien/binexport

I will upstream the fix in the next days -- it works for BinNavi, but I need to ensure that there are no Google-internal regressions caused by my fix.

So TL;DR: If you rebuild binexport from my fork, it *should* work. Good luck!

**Comment by luckycat889** [comment] 2017-05-17 02:42
That's awesome! Thanks for looking into this, and providing a fix.

I use IDA on MS Win, and I love to try out the fix. However, first I'd need to dig up a copy of VS...
Once you have upstreamed the fix, I assume they will also publish the pre-built plugins on the 'release' github page? Just in case I don't find a copy of VS....

Again, appreciate the fix!

**Comment by thomasdullien** [comment] 2017-05-17 06:16
Hey there,

yes, once the upstream is fixed I will try to post a VS build. Please be aware of 
   https://github.com/google/binnavi/issues/107 -- e.g. you will still get an error message
on import in BinNavi (albeit none from IDA), and everything will be fine.

Cheers,
Thomas

**Comment by luckycat889** [comment] 2017-05-25 15:55
I went ahead trying to compile; I only have access to Visual Studio 2017 community ed. 
With some small changes here and there, it builds....until postgres, which seems very hard-wired to 2015.

If it's not too much trouble, would it be possible for you to put the precompiled plugins somewhere.
I am sure others would appreciate that as well.

Thanks!

**Comment by DigiAngel** [comment] 2017-05-25 15:57
+1 to precompiled

**Comment by thomasdullien** [comment] 2017-05-25 16:51
Hey there,

I will try to set up a win32 / win64 build environment -- I don't currently have one - and then keep this thread posted :-).

It is *possible* (although by no means certain) that reverting to a precompiled version in this repository from an older BinNavi (perhaps the initial commit?) may work, too.

**Comment by luckycat889** [comment] 2017-05-26 18:24
I made a mistake installing VS 2015 before, I did it again, and with some tinkering, I built the plugins.
I build binnavi from source, after adding the plugins to the source folder, and I run it, connect to a postgres db, and everything works fine. I import a .i64 file, and the IDA export seemingly works, I open the binnavi module I imported, I see that 2800 functions are there, but when trying to initialize the module, it says
The module 'xxx' could not be initialized

Possible causes:
- There was a problem with the database connection.

My connection though, seems to be fine, I could ( I think the import of the IDA db worked).

Any ideas what to do next??

[binexport_win_plugins.zip](https://github.com/google/binnavi/files/1032685/binexport_win_plugins.zip)

**Comment by thomasdullien** [comment] 2017-08-23 18:58
Hey there,

apologies for having this left dangling, should get around to it in the next days.

**Comment by luckycat889** [comment] 2017-09-05 16:30
That would be great! As mentioned earlier in this thread; I gave it a whirl, built it from your fork, but I ran into these other problems.

Thanks!

**Comment by legion2000** [comment] 2017-11-28 02:39
Any updates? Thanks.

**Comment by cblichmann** [comment] 2020-04-26 16:17
The BinNavi project is no longer under active development.

**Closed by cblichmann** 2020-04-26 16:17 UTC
